# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

OrdererOrgs:

  - Name: Orderer
    Domain: workspace
    EnableNodeOUs: true
    Template:
      Start: 1
      Count: 5
      

PeerOrgs:
  - Name: healthcare
    Domain: healthcare.workspace
    EnableNodeOUs: true
    Template:
      Start: 1
      Count: 2
    Users:
      Start: 1
      Count: 1

  - Name: research
    Domain: research.workspace
    EnableNodeOUs: true
    Template:
      Start: 1
      Count: 2
    Users:
      Count: 1
  
  - Name: thirdparty
    Domain: thirdparty.workspace
    EnableNodeOUs: true
    Template:
      Start: 1
      Count: 2
    Users:
      Start: 1
      Count: 1

